add getCancellationReason endpoint to ManagmentOrderController
ita-social-projects/GreenCityUBS pull request #1048
Opened 2023-03-15 14:40 UTC by KharchenkoV

dev
## Sumary of issue:
Need to add new endpoint for getting cancellation reason and comment

bug
[#5479](https://github.com/ita-social-projects/GreenCity/issues/5479)

## Summary of change
ManagmentOrderController  added getOrderCancellationReason method
ManagmentOrderController made test for getOrderCancellationReason method
UBSManagmentService added getOrderCancellationReason method
UBSManagmentServiceImpl implemented getOrderCancellationReason method
UBSManagmentServiceImplTest made test for getOrderCancellationReason method
SecurityConfig added  "/ubs/management/get-order-cancellation-reason/{id}" endpoint 

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-16 10:35 UTC, RomaMocherniuk commented on core/src/test/java/greencity/controller/ManagementOrderControllerTest.java
> +        this.mockMvc.perform(get(ubsLink + "/get-order-cancellation-reason" + "/{id}", 1L))
please add `verify` that` ubsManagementService.getOrderCancellationReason` is called with expected params

2023-03-16 10:36 UTC, RomaMocherniuk commented on service-api/src/main/java/greencity/service/ubs/UBSManagementService.java
> +     * Method returns cancellation reason and comment to order.
please add `id` to javadoc

2023-03-16 10:37 UTC, RomaMocherniuk commented on service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java
> +            .orElseThrow(() -> new NotFoundException(ORDER_WITH_CURRENT_ID_DOES_NOT_EXIST));
please add test if` NotFoundException(ORDER_WITH_CURRENT_ID_DOES_NOT_EXIST)`

2023-03-16 10:39 UTC, RomaMocherniuk commented on service/src/test/java/greencity/service/ubs/UBSManagementServiceImplTest.java
> +        when(orderRepository.findById(anyLong())).thenReturn(Optional.ofNullable(order));
please do not use `anyLong()`
It is better to use expected `orderId`
And please add `verify`

2023-03-16 10:42 UTC, RomaMocherniuk commented on core/src/main/java/greencity/controller/ManagementOrderController.java
> +        @ApiResponse(code = 404, message = HttpStatuses.NOT_FOUND)
I see that we can have next responses:

- `200` - success
- `401` - unauthorized user
- `403` - used does not have the required role
- `404` - order with `orderId` does not exist

When can we have `400` response?

2023-03-16 10:47 UTC, RomaMocherniuk commented on core/src/main/java/greencity/controller/ManagementOrderController.java
> +    @GetMapping("/get-order-cancellation-reason/{id}")
I see that there is a similar endpoint in `OrderController`
```
 @GetMapping("/order/{id}/cancellation")
    public ResponseEntity<OrderCancellationReasonDto> getCancellationReason(
```
Why do we need one more?
can we modify the existing endpoint?

2023-03-16 11:00 UTC, RomaMocherniuk requested changes
Left some comments

2023-03-17 10:13 UTC, KharchenkoV commented on core/src/test/java/greencity/controller/ManagementOrderControllerTest.java
> +        this.mockMvc.perform(get(ubsLink + "/get-order-cancellation-reason" + "/{id}", 1L))
done

2023-03-17 10:13 UTC, KharchenkoV commented on service-api/src/main/java/greencity/service/ubs/UBSManagementService.java
> +     * Method returns cancellation reason and comment to order.
done

2023-03-17 10:13 UTC, KharchenkoV commented on service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java
> +            .orElseThrow(() -> new NotFoundException(ORDER_WITH_CURRENT_ID_DOES_NOT_EXIST));
done

2023-03-17 10:13 UTC, KharchenkoV commented on service/src/test/java/greencity/service/ubs/UBSManagementServiceImplTest.java
> +        when(orderRepository.findById(anyLong())).thenReturn(Optional.ofNullable(order));
done

2023-03-17 10:13 UTC, KharchenkoV commented on core/src/main/java/greencity/controller/ManagementOrderController.java
> +    @GetMapping("/get-order-cancellation-reason/{id}")
We need another one only for admin

2023-03-17 10:42 UTC, RomaMocherniuk approved these changes

2023-03-17 10:49 UTC, LiliaMokhnatska approved these changes

2023-03-17 10:54 UTC, ABbondar approved these changes

2023-03-17 11:01 UTC, MaksymGolik approved these changes

2023-03-17 11:01 UTC, merged