Created two controllers, first controller returns info about user, ubs…
ita-social-projects/GreenCityUBS pull request #145
Opened 2021-06-11 07:28 UTC by rusanovscaia

…_user and user violation, second contorller updates ubs_user info in order

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-06-11 09:07 UTC, DanylkoMykola approved these changes

2021-06-11 09:10 UTC, ZaharVeremchuk requested changes
Test coverage , code smells( not var, not name)

2021-06-11 09:35 UTC, rusanovscaia commented
> 
> 
> Test coverage , code smells( not var, not name)

sure, working on it

2021-06-11 10:06 UTC, KwintiukN approved these changes

2021-06-16 12:54 UTC, ZaharVeremchuk approved these changes

2021-06-16 12:55 UTC, merged