Order detail
ita-social-projects/GreenCityUBS pull request #147
Opened 2021-06-16 11:23 UTC by OrestIT

Added three new controllers for custom information (Basic information, update information, amount calculation)

2021-06-19 09:37 UTC, ZaharVeremchuk requested changes
min 60 % then approve 

![image](https://user-images.githubusercontent.com/45737995/122638129-1bff0a80-d0fb-11eb-905c-232b0454e005.png)

2021-06-20 09:32 UTC, rusanovscaia approved these changes

2021-06-20 09:35 UTC, DanylkoMykola approved these changes

2021-06-21 07:12 UTC, ZaharVeremchuk approved these changes

2021-06-21 08:10 UTC, merged