Refactored some functionality for order's and super admin
ita-social-projects/GreenCityUBS pull request #535
Opened 2021-12-01 08:23 UTC by VadymMakitra

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-12-01 11:08 UTC, yurabh approved these changes

2021-12-01 11:09 UTC, KuzbytMaksym approved these changes

2021-12-06 18:50 UTC, DimaSannytski approved these changes

2021-12-10 07:52 UTC, thesvider commented on core/src/main/java/greencity/controller/SuperAdminController.java
> +    @DeleteMapping("/deleteCourier/{id}")
please check https://restfulapi.net

2021-12-10 07:53 UTC, thesvider commented on core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
> +        log.trace(ex.getMessage(), ex);
any specific reason you keep log level as trace here?

2021-12-10 07:55 UTC, thesvider commented on dao/src/main/java/greencity/entity/order/CourierLocations.java
> +public class CourierLocations {
Class name should be singular.  `CourierLocation` instead

2021-12-10 07:57 UTC, thesvider commented on dao/src/main/java/greencity/entity/order/CourierLocations.java
> +    @Column(name = "max_price_of_order")
I think name is not required as long column name can be resolved based on fieldName.
In this case `maxPriceOfOrder` will be resolved into column `max_price_of_order`
`
@Column
private Long maxPriceOfOrder;
`

2021-12-10 08:07 UTC, thesvider commented on service/src/main/java/greencity/mapping/AddLocationDtoMapper.java
> +    protected AddLocationDto convert(Location source) {
AddLocationDto sounds like method. rename to something like `LocationCreateDto`

2021-12-10 08:09 UTC, thesvider commented on service/src/main/java/greencity/mapping/AddLocationDtoMapper.java
> +        List<LocationTranslation> locationTranslations = new ArrayList<>(source.getLocationTranslations());
I don't understand why do you need another collection `locationTranslations`. Can't you just loop 
`source.getLocationTranslations()` directly?

2021-12-10 08:13 UTC, thesvider commented on service/src/main/java/greencity/mapping/AddServiceDtoMapper.java
> +        source.setFullPrice(source.getPrice() + source.getCommission());
Why are you modifying state of the source in Mapper?
If you need to have full price calculated - define method `getFullPrice` in class `Bag` that will be adding price to commision.
Another problem I see here - you calculate full price but do not include it in `AddServiceDto`

2021-12-10 08:13 UTC, thesvider commented on service/src/main/java/greencity/mapping/AddServiceDtoMapper.java
> +        List<TariffTranslationDto> dto = translations.stream().map(
bad name dto for a list. Use dtoList or something.

2021-12-10 08:17 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +        if (courierLocations.getCourierLimit().equals(CourierLimit.LIMIT_BY_SUM_OF_ORDER)) {
simplify this logic. `if` inside of `if` is hard to read

2021-12-10 08:20 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +        if (courierLocations.getCourierLimit().equals(CourierLimit.LIMIT_BY_AMOUNT_OF_BAG)) {
to avoid NPE, rewrite to 
`CourierLimit.LIMIT_BY_AMOUNT_OF_BAG.equals(courierLocations.getCourierLimit())`.

2021-12-10 08:21 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +            checkAmountOfBagsIfCourierLimitByAmountOfBag(courierLocations, bigBagCounter);
Please extract 120 into private static final Integer field.

2021-12-10 08:22 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +        if (courierLocations.isEmpty()) {
extract language code `"ua"` into constant. You can have separate class with country codes if it is applicable somewhere else in code.

2021-12-10 14:13 UTC, thesvider requested changes
Please resolve comments

2021-12-12 15:49 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +    public static final String langCode = "ua";
according to convention, constants should have name like: LANG_CODE, BAGS_CAPACITY etc

2021-12-12 15:50 UTC, thesvider approved these changes

2021-12-12 20:27 UTC, Zingerd approved these changes

2021-12-18 00:14 UTC, merged