Order page
ita-social-projects/GreenCityUBS pull request #585
Opened 2021-12-23 14:27 UTC by VadymMakitra

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-12-23 17:57 UTC, Natalia1910 approved these changes

2021-12-23 19:59 UTC, Max877866 approved these changes

2021-12-24 09:11 UTC, thesvider commented on core/src/main/java/greencity/controller/SuperAdminController.java
> +     * @return {@link FindInfoAboutLocationDto}
`FindInfoAboutLocationDto` is not the best name for the class. Give it `LocationInfoDto` or something.

2021-12-24 09:12 UTC, thesvider commented on core/src/main/java/greencity/controller/SuperAdminController.java
> +        @ApiResponse(code = 201, message = HttpStatuses.OK),
looks misleading. code 200 corresponds to OK actually.

2021-12-24 09:15 UTC, thesvider commented on core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(exceptionResponce);
You don't need to have multiple ExceptionHandlers that return the same BadRequest. You can define one handler and keep list of Exceptions in @ ExceptionHandler annotation

2021-12-24 09:17 UTC, thesvider commented on core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java
> +    public final ResponseEntity<Object> handleLocationAlreadyCreatedException(LocationAlreadyCreatedException ex,
please make sure you have Controller test that verifies case with BadRequest

2021-12-24 09:18 UTC, thesvider commented on dao/src/main/java/greencity/entity/user/Region.java
> +    private List<Location> locationList;
rename to `locations`

2021-12-24 09:18 UTC, thesvider commented on dao/src/main/java/greencity/entity/user/Region.java
> +    private List<RegionTranslation> regionTranslation;
rename to `regionTranslations`

2021-12-24 09:20 UTC, thesvider commented on dao/src/main/java/greencity/repository/LocationRepository.java
> +    Location findLocationByName(@Param("locationName") String locationName);
if location is not found by name, you'll get null, right? Good practice is to use Optional as a return type instead.

2021-12-24 09:21 UTC, thesvider commented on dao/src/main/java/greencity/repository/RegionRepository.java
> +    Region findRegionByName(@Param("name") String name);
use `Optional<Region>` as a return type.

2021-12-24 09:23 UTC, thesvider commented on service-api/src/main/java/greencity/constant/ErrorMessage.java
> +    public static final String REGION_IS_NOT_FOUND = "Region with chosen name doesn't found ";
`doesn't found ` is not grammatically correct. Use: `Region with chosen name doesn't exist`, for example

2021-12-24 09:26 UTC, thesvider commented on service-api/src/main/java/greencity/dto/NewLocationForCourierDto.java
> +    private Long minAmountOfBigBag;
for min/max it's better to introduce class Range with two fields: min and max

2021-12-28 14:52 UTC, thesvider commented on service-api/src/main/java/greencity/dto/RangeDto.java
> +@Setter
not a good practice to havre both builder and setter. You can achieve immutability if you avoid usage of setters here. So your object will be built using Builder only. Also, please review if there are other redundant annotations.

2021-12-28 14:54 UTC, thesvider commented on service/src/main/java/greencity/mapping/FindAllInfoAboutLocationDtoMapper.java
> +        List<LocationsDto> locationsDtoList = source.getLocations().stream()
code is not correctly formatted. Use Ctrl + alt + L

2021-12-28 14:55 UTC, thesvider commented on service/src/main/java/greencity/mapping/FindAllInfoAboutLocationDtoMapper.java
> +            .map(i -> new LocationsDto(i.getId(), i.getLocationStatus().toString(), i.getCoordinates().getLatitude(),
bad name for variable - `i`. Give it some meaningful name

2021-12-28 14:55 UTC, thesvider commented on service/src/main/java/greencity/mapping/FindAllInfoAboutLocationDtoMapper.java
> +                    .map(j -> new LocationTranslationDto(j.getLocationName(), j.getLanguage().getCode()))
the same with `j`

2021-12-28 14:57 UTC, thesvider commented on service/src/main/java/greencity/mapping/FindAllInfoAboutLocationDtoMapper.java
> +            .map(i -> new LocationsDto(i.getId(), i.getLocationStatus().toString(), i.getCoordinates().getLatitude(),
to create `LocationsDto` it's better to use builder instead of constructor with 4 arguments

2021-12-28 15:03 UTC, thesvider commented on service/src/main/java/greencity/mapping/GetCourierLocationMapper.java
> +            i -> new LocationsDto(i.getId(), i.getLocationStatus().toString(), i.getCoordinates().getLatitude(),
code is not formatted. use ctrl + alt + L

2021-12-28 15:04 UTC, thesvider commented on service/src/main/java/greencity/mapping/GetCourierLocationMapper.java
>          List<Location> locations = List.of(source.getLocation());
what's the point fo creating the list of single element?

2021-12-28 15:05 UTC, thesvider commented on service/src/main/java/greencity/mapping/GetCourierLocationMapper.java
> +            i -> new LocationsDto(i.getId(), i.getLocationStatus().toString(), i.getCoordinates().getLatitude(),
give it better names instead of `i` and `j`. This is not MatLab )

2021-12-28 15:06 UTC, thesvider commented on service/src/main/java/greencity/mapping/GetCourierLocationMapper.java
> +            i -> new LocationsDto(i.getId(), i.getLocationStatus().toString(), i.getCoordinates().getLatitude(),
use builders instead of constructors with big number of arguments

2021-12-28 15:07 UTC, thesvider commented on service/src/main/java/greencity/mapping/LocationCreateDtoMapper.java
> +        List<AddLocationTranslationDto> dtos = source.getLocationTranslations().stream().map(
similar comments as for other mappers

2021-12-28 15:15 UTC, thesvider requested changes
resolve comments.

2021-12-29 20:35 UTC, thesvider approved these changes

2021-12-30 01:35 UTC, merged