Add new DTO for updateUserData and add validation for field additionalOrders
ita-social-projects/GreenCityUBS pull request #594
Opened 2021-12-29 21:43 UTC by Natalia1910

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-12-29 21:54 UTC, VadymMakitra requested changes

2021-12-29 21:54 UTC, VadymMakitra commented on service/src/main/java/greencity/mapping/UserToUserProfileUpdateDto.java
> +        List<AddressDto> addressDtoList = addresses.stream()
Is it need to create list of Address? Why not write user.getAddresses .stream()... ?

2021-12-29 21:54 UTC, VadymMakitra commented on service/src/main/java/greencity/mapping/UserToUserProfileUpdateDto.java
> +            .map(address -> new AddressDto(address.getId(), address.getCity(), address.getDistrict(),
Will be better if you build this Object.

2021-12-29 21:54 UTC, VadymMakitra commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
>              addressDtoList.stream().map(a -> modelMapper.map(a, Address.class)).collect(Collectors.toList());
same with mapper. Why not write serProfileUpdateDto.getAddressDto().stream()...

2021-12-29 21:56 UTC, VadymMakitra commented on service/src/main/java/greencity/mapping/UserToUserProfileUpdateDto.java
> +public class UserToUserProfileUpdateDto extends AbstractConverter<User, UserProfileUpdateDto> {
Please add test for this mapper.

2021-12-29 21:57 UTC, Max877866 approved these changes

2021-12-29 22:26 UTC, RossSihovsk approved these changes

2021-12-30 08:08 UTC, thesvider requested changes
Please resolve comments

2021-12-30 11:14 UTC, VadymMakitra approved these changes

2021-12-30 11:31 UTC, thesvider commented on service/src/main/java/greencity/mapping/UserToUserProfileUpdateDtoMapper.java
> +            .map(address -> AddressDto.builder()
add `private AddressDto createAdressDto(Address)` method

2021-12-30 11:47 UTC, thesvider approved these changes

2021-12-30 11:47 UTC, merged