refactoring some fields
ita-social-projects/GreenCityUBS pull request #621
Opened 2022-01-18 19:23 UTC by Zingerd

2022-01-19 09:02 UTC, Natalia1910 approved these changes

2022-01-19 09:06 UTC, RossSihovsk approved these changes

2022-01-19 09:38 UTC, thesvider commented on core/src/main/java/greencity/controller/OrderController.java
> +    private String greenCityClient;
preferred way is to use ConfigProperties class instead of injecting @ Value here. @VadymMakitra used that approach in one of his PRs.

2022-01-19 09:39 UTC, VadymMakitra approved these changes

2022-01-19 09:39 UTC, thesvider commented on core/src/test/java/greencity/controller/OrderControllerTest.java
> +        Field[] fields = OrderController.class.getDeclaredFields();
what is happening here?

2022-01-19 09:39 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +            .orderId(String.format("%s_%s_%s", orderId, order.getCounterOrderPaymentId(),
I think we agreed to have some Util class that will incapsulate "%s_%s_%s" logic.

2022-01-19 09:40 UTC, thesvider requested changes
please resolve comments

2022-01-20 07:37 UTC, thesvider approved these changes

2022-01-20 12:40 UTC, merged