only numeric characteristic condition
ita-social-projects/GreenCityUBS pull request #629
Opened 2022-01-24 18:07 UTC by RossSihovsk

2022-01-24 18:43 UTC, Natalia1910 approved these changes

2022-01-24 18:58 UTC, KuzbytMaksym approved these changes

2022-01-25 08:43 UTC, VadymMakitra requested changes

2022-01-25 08:43 UTC, VadymMakitra commented on service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java
> +                    if (!newNumber.matches("[0-9]+") || newNumber.length() != 10) {
Use filter instead of if loop.

2022-01-25 09:08 UTC, VadymMakitra commented
Please resolve coment

2022-01-25 14:46 UTC, VadymMakitra approved these changes

2022-01-25 15:28 UTC, merged