created new column and deleted language_id
ita-social-projects/GreenCityUBS pull request #676
Opened 2022-02-10 15:51 UTC by Zingerd

created a new column and deleted language_id and also refactoring some methods

2022-02-10 15:52 UTC, Max877866 approved these changes

2022-02-10 15:56 UTC, Bohdan-Melnyk approved these changes

2022-02-10 15:56 UTC, VadymMakitra requested changes

2022-02-10 15:56 UTC, VadymMakitra commented on service/src/test/java/greencity/service/SuperAdminServiceImplTest.java
> +//    @Test
Remove cpmment's

2022-02-10 16:00 UTC, VadymMakitra requested changes

2022-02-10 16:00 UTC, VadymMakitra commented on service/src/test/java/greencity/ModelUtils.java
> +//            .languageId(1L)
remove comment's

2022-02-10 16:00 UTC, VadymMakitra commented on service/src/test/java/greencity/service/SuperAdminServiceImplTest.java
> +//        when(languageRepository.findById(1L)).thenReturn(Optional.of(ModelUtils.getLanguage()));
!

2022-02-10 16:00 UTC, VadymMakitra commented on service/src/test/java/greencity/service/SuperAdminServiceImplTest.java
> +//            .language(Language.builder().id(1L).code("en").build())
!

2022-02-10 16:00 UTC, VadymMakitra commented
Please resolve comments!

2022-02-10 17:38 UTC, thesvider approved these changes

2022-02-10 17:39 UTC, thesvider requested changes
Resolve code smells

2022-02-10 19:33 UTC, thesvider approved these changes

2022-02-10 19:34 UTC, thesvider approved these changes

2022-02-11 00:50 UTC, VadymMakitra approved these changes

2022-02-11 09:37 UTC, merged