#3804 create new logic to get all locations
ita-social-projects/GreenCityUBS pull request #696
Opened 2022-02-16 18:30 UTC by Bohdan-Melnyk

Add neAPI for pricing page

2022-02-17 10:21 UTC, VadymMakitra commented on core/src/main/java/greencity/controller/SuperAdminController.java
> +    @GetMapping("/getAllTariffs")
It's not rest style please check https://restfulapi.net/

2022-02-17 10:27 UTC, VadymMakitra commented on dao/src/main/java/greencity/entity/order/Bag.java
> +    TariffsInfo tariffsInfo;
You were forgetting about access modifier;

2022-02-17 10:43 UTC, VadymMakitra requested changes

2022-02-17 10:43 UTC, VadymMakitra commented on dao/src/main/java/greencity/entity/order/CourierLocation.java
> +    TariffsInfo tariffsInfo;
You were forgetting about access modifier;

2022-02-17 10:43 UTC, VadymMakitra commented on dao/src/main/java/greencity/entity/order/Service.java
> +    private TariffsInfo tariffsInfo;
!

2022-02-17 10:43 UTC, VadymMakitra commented on dao/src/main/resources/db/changelog/logs/20220902-ch-add-table-tariffs-info-Melnyk.xml
> +<!--                                 constraintName="blabla"/>-->
Remove comment's;

2022-02-17 10:43 UTC, VadymMakitra commented on service/src/main/java/greencity/mapping/GetTariffsInfoDtoMapper.java
> +        List<Location> locations = courierLocations.stream()
Will be better if you write here source source.getCourierLocations().stream() and remove courierLocations;

2022-02-17 14:30 UTC, VadymMakitra commented
Resolve comments

2022-02-17 14:33 UTC, VadymMakitra requested changes

2022-02-17 14:33 UTC, VadymMakitra commented on service/src/main/java/greencity/service/ubs/SuperAdminServiceImpl.java
> +            .map(i -> modelMapper.map(i, GetTariffsInfoDto.class))
rename variable i;

2022-02-21 15:33 UTC, Max877866 approved these changes

2022-02-21 15:34 UTC, Natalia1910 approved these changes

2022-02-21 15:41 UTC, thesvider commented on dao/src/main/java/greencity/entity/enums/LocationStatus.java
> +    LocationStatus() {
you can use lombok annotations for constructors and methods

2022-02-21 16:00 UTC, KuzbytMaksym approved these changes

2022-02-22 11:19 UTC, Natalia1910 approved these changes

2022-02-22 11:19 UTC, Max877866 approved these changes

2022-02-22 11:48 UTC, VadymMakitra approved these changes

2022-02-22 11:50 UTC, merged

2022-02-23 20:32 UTC, thesvider commented on dao/src/main/java/greencity/entity/user/User.java
> +    @OneToMany(fetch = FetchType.LAZY, mappedBy = "creator")
I think fetch type is Lazt by default, no need to declare

2022-02-23 20:34 UTC, thesvider commented on dao/src/main/resources/db/changelog/logs/20221002-ch-add-column-creator-id-in-tariffs-info-table-Melnyk.xml
> +        <addColumn tableName="tariffs_info">
why are you keeping separately add column for tariffs_info? You've created this table in 20220902-ch-add-table-tariffs-info-Melnyk.xml so why don't you declare all the needed columns there?

2022-02-23 20:35 UTC, thesvider commented on service/src/main/java/greencity/mapping/GetTariffsInfoDtoMapper.java
> +            .collect(Collectors.toList());
can you simplify this method? create a few private methods instead.