Fix bugs with translations
ita-social-projects/GreenCityUBS pull request #710
Opened 2022-03-25 12:31 UTC by Pavl0-Gural

Fix 500 error when try to change language from eng to ua

2022-03-25 12:59 UTC, SomeOne35719 approved these changes

2022-03-25 15:48 UTC, VadymMakitra reviewed
Please resolve comment's

2022-03-25 15:48 UTC, VadymMakitra commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +            } else if (languageId == 2) {
why you don't use the binary operator OR ( || )
 if(translations.size() == 1) || languageId == 2) ?

2022-03-25 15:48 UTC, VadymMakitra commented on core/src/main/java/greencity/controller/ClientController.java
> +    public ResponseEntity<PageableDto<OrderStatusForUserDto>> getAllDataForOrder(
Please check https://restfulapi.net/

2022-03-25 15:51 UTC, VadymMakitra commented
![image](https://user-images.githubusercontent.com/84317209/160155014-c21a21dd-6037-4648-9646-f9b6f028560e.png)
You pr have only 36 % of coverage. Please up the coverage of you pr at least to 70 %

2022-03-25 15:52 UTC, VadymMakitra requested changes
Please resolve comments

2022-04-10 18:26 UTC, VadymMakitra commented
@Pavl0-Gural Please resolve previous comment's

2022-04-11 16:24 UTC, VadymMakitra reviewed
Please resolve comment;

2022-04-11 16:24 UTC, VadymMakitra commented on core/src/main/java/greencity/controller/ClientController.java
> +    @GetMapping("/get-all-orders-data")
please change the web address to the rest API standard. Additional info here.

2022-04-12 10:04 UTC, VadymMakitra approved these changes

2022-04-12 10:22 UTC, Andrii-Yezenitskyi approved these changes

2022-04-14 07:08 UTC, thesvider commented on core/src/main/java/greencity/controller/ClientController.java
> +    @GetMapping("/get-user-orders")
avoid using "get" in URL name. read this: https://restfulapi.net/resource-naming/

2022-04-14 07:11 UTC, thesvider commented on core/src/main/java/greencity/controller/ClientController.java
>          @ApiResponse(code = 404, message = HttpStatuses.NOT_FOUND)
This API never retirns 404, please keep doc up to date.

2022-04-14 07:14 UTC, thesvider commented on dao/src/main/resources/db/changelog/logs/ch-update-order_payment_status_translations-Hural.xml
> +    <changeSet id="Hural-3" author="Pavlo Hural">
no need to have 2 separate changesets Hural-3 and Hural-4. You can merge them into single one

2022-04-14 07:18 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
>          for (Order order : orders) {
Simplify this loop. You can use stream + introduce private methods

2022-04-14 07:20 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +    private List<CertificateDto> getCertificate(Set<Certificate> certificates) {
this logic should be in mapper.

2022-04-14 07:22 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +        for (Certificate certificate : certificates) {
`    private List<CertificateDto> getCertificate(Set<Certificate> certificates) {
        return certificates.stream()
                .map(certificate -> CertificateDto.builder()
                        .certificateDate(certificate.getCreationDate())
                        .certificateStatus(certificate.getCertificateStatus().name())
                        .certificatePoints(certificate.getPoints())
                        .code(certificate.getCode())
                        .build())
                .collect(Collectors.toList())
    }`

2022-04-14 07:32 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java
> +                : "order status english not found";
this is wrong. I'd better return enum value (OrderStatus) than this message. It's confusing for user

2022-04-14 07:34 UTC, thesvider commented on service/src/main/java/greencity/service/ubs/UBSManagementServiceImpl.java
> +            currentOrder = order.get();
it's better to use Optional streams instead fof these condition on isPresent

2022-04-14 07:35 UTC, thesvider requested changes
please resolve comments

2022-04-20 17:55 UTC, thesvider approved these changes

2022-04-21 13:49 UTC, merged