[UBS] Fixed bugs in order controller
ita-social-projects/GreenCityUBS pull request #713
Opened 2022-03-30 14:43 UTC by Andrii-Yezenitskyi

Fixed bugs specified in issues 3943, 3944.
Changed [/ubs/{id}/delete-order-address] HTTP method from POST to DELETE.
Fixed 
error 500 in [/ubs/getLiqPayStatus/{orderId}] when trying to get status for order with 2 or more payments.

2022-03-30 15:37 UTC, VadymMakitra requested changes

2022-03-30 15:37 UTC, VadymMakitra commented on core/src/main/java/greencity/controller/OrderController.java
> +    @DeleteMapping("/{id}/delete-order-address")
Please check https://restfulapi.net/

2022-03-30 15:37 UTC, VadymMakitra commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +        Payment payment = payments.get(payments.size() - 1);
What will be if the list is empty?

2022-03-30 15:49 UTC, Andrii-Yezenitskyi commented on service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java
> +        Payment payment = payments.get(payments.size() - 1);
The list cannot be empty because otherwise exception will be thrown here: https://github.com/ita-social-projects/GreenCityUBS/blob/988931feca27d9665a97d817c09c493d2cd73fc9/service/src/main/java/greencity/service/ubs/UBSClientServiceImpl.java#L1096-L1101

2022-03-30 17:36 UTC, Andrii-Yezenitskyi commented on core/src/main/java/greencity/controller/OrderController.java
> +    @DeleteMapping("/{id}/delete-order-address")
Please specify your point

2022-04-04 17:33 UTC, Pavl0-Gural approved these changes

2022-04-04 18:18 UTC, VadymMakitra approved these changes

2022-04-05 12:31 UTC, Max877866 approved these changes

2022-04-05 13:08 UTC, yourromchikkkkk approved these changes

2022-04-07 11:25 UTC, merged