Dto refactoring
ita-social-projects/GreenCityUBS pull request #741
Opened 2022-04-30 18:42 UTC by danylohlynsky

Refactored all dtos in service-api and split it into smaller packages

2022-04-30 20:43 UTC, VadymMakitra requested changes

2022-04-30 20:43 UTC, VadymMakitra commented on service-api/src/main/java/greencity/dto/payment/PaymentResponseDto.java
> +    private String orderId;
Please revert this dto to the previous state, this is a part of logic. If you rename the fields you drop this logic.

2022-05-02 09:55 UTC, VadymMakitra approved these changes

2022-05-02 09:56 UTC, Max877866 approved these changes

2022-05-03 11:49 UTC, Pavl0-Gural approved these changes

2022-05-03 12:13 UTC, merged