[UBS] - rename from location_status to tariff_status in tariffs_info table #4874
ita-social-projects/GreenCityUBS pull request #982
Opened 2023-02-01 13:36 UTC by sergoliarnik

# UBS rename from location_status to tariff_status in tariffs_info table 

## Summary Of Issue :
# UBS rename from location_status to tariff_status in tariffs_info entity

## Issue Link :
https://github.com/ita-social-projects/GreenCity/issues/4874

## Summary Of Changes :
1. rename from location_status to tariff_status in tariffs_info table
2. rename from locationStatus to tariffStatus in code
3. create TariffStatus enum with the same fields as in the LocationStatus

## Code reviewers

- [ ] @github_username

## Added
- TariffStatus enum

## Changed 
- tariffs_info table
- rename from location_status to tariff_status in tariffs_info table
- rename from locationStatus to tariffStatus in code

## CHECK LIST
- [x] Code is up-to-date with the `dev` branch.
- [x] You've successfully built and run the tests locally.
- [x] There are new or updated unit tests validating the change.
- [x] JIRA/ Github Issue number & title in PR title (ISSUE-https://github.com/ita-social-projects/GreenCity/issues/4874: Ticket title)
- [x] This template filled (above this section).
- [ ] Sonar's report does not contain bugs, vulnerabilities, security issues, code smells ar duplication
- [x] `NEED_REVIEW` and `READY_FOR_REVIEW` labels are added.
- [x] All files reviewed before sending to reviewers

2023-02-14 08:43 UTC, RomaMocherniuk commented on dao/src/main/java/greencity/enums/TariffStatus.java
> +    ACTIVE(1, "Активно"), NEW(2, "Новостворено"), DEACTIVATED(3, "Неактивно");
Why do you use Ukrainian here?

2023-02-14 08:48 UTC, RomaMocherniuk commented on dao/src/main/java/greencity/enums/TariffStatus.java
> +    private String status;
`priority` and `status` are never used
Why do we need these fields?

2023-02-14 08:51 UTC, RomaMocherniuk commented on dao/src/main/java/greencity/enums/TariffStatus.java
> +@NoArgsConstructor
Constructor of enum should be `private`

2023-02-15 08:32 UTC, RomaMocherniuk approved these changes

2023-02-15 13:00 UTC, RomaMocherniuk requested changes
Please add tests for `TariffsInfoSpecification.toPredicate()` mrthod

2023-03-03 09:25 UTC, JJJazl approved these changes

2023-03-03 09:41 UTC, juseti approved these changes

2023-03-03 11:04 UTC, MaksymGolik approved these changes

2023-03-20 11:32 UTC, merged